// Generated by CoffeeScript 1.6.3
(function() {
  var ajaxParams, imageBox;

  ajaxParams = {
    apiUrl: "https://secure.flickr.com/services/rest/?method=flickr.people.getPublicPhotos",
    options: {
      format: "json",
      nojsoncallback: 1,
      api_key: "1684af1009448d6b66290bd7dedac4e3",
      user_id: "80451209@N04",
      extras: "description, tags"
    }
  };

  imageBox = function(photo) {
    var image_template;
    this.url = "http://www.flickr.com/photos/daniseating/" + photo.id + "/in/photostream";
    this.src = "http://farm" + photo.farm + ".static.flickr.com/" + photo.server + "/" + photo.id + "_" + photo.secret + "_" + "m.jpg";
    this.title = photo.title;
    this.description = photo.description._content;
    this.tags = photo.tags;
    image_template = "        <div class='item {{tags}}'>            <img src='{{{src}}}' title='{{title}}}' />            <p class='label'>                <span>{{{title}}}</span>            </p>            <div class='metadata'>                <p>{{{description}}}</p>                <a class='goFlickr' href='{{url}}' target='_blank' title='View this photo on flickr'>flickr!</a>            </div>        </div>";
    this.build = function() {
      var renderBox;
      renderBox = window.Handlebars.compile(image_template);
      return renderBox(this);
    };
  };

  $.getJSON(ajaxParams.apiUrl, ajaxParams.options, function(data) {
    var tag, tags, _i, _len;
    tags = [];
    $.each(data.photos.photo, function() {
      var markup;
      markup = new imageBox(this).build();
      $("#container").append(markup);
      if (jQuery.inArray(this.tags, tags) === -1 && this.tags !== "") {
        if (this.tags.indexOf("uploaded:by=flickrmobile flickriosapp:filter=nofilter") === -1) {
          tags.push(this.tags);
        }
      }
    });
    for (_i = 0, _len = tags.length; _i < _len; _i++) {
      tag = tags[_i];
      $("ul#taglist").append("<li><a href='javascript:;' id='." + tag + "'>" + tag + "</a>");
      void 0;
    }
    $("#container").imagesLoaded(function() {
      $("#container").isotope({
        itemSelector: ".item",
        animationOptions: {
          duration: 750,
          easing: 'linear',
          queue: false
        }
      });
    });
  });

}).call(this);
